{{- if .Values.gateway.rolloutJob.enabled }}
{{- if .Values.global.glooRbac.create }}
{{- if not .Values.global.glooRbac.namespaced -}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gloo-resource-rollout{{ include "gloo.rbacNameSuffix" . }}
  labels:
{{ include "gloo.labels" . | indent 4}}
    gloo: rbac
roleRef:
  kind: ClusterRole
  name: gloo-resource-rollout{{ include "gloo.rbacNameSuffix" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: gloo-resource-rollout
  namespace: {{ .Release.Namespace }}
{{- end }}{{/* if not .Values.global.glooRbac.namespaced */}}
{{- end -}}{{/* if .Values.global.glooRbac.create */}}
{{- end }}{{/* if .Values.gateway.rolloutJob.enabled  */}}
